# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: npm
    directories: 
      - /
      - /examples/node-cjs
      - /examples/node-esm
      - /examples/node-esm-environments
      - /examples/node-esm-jsx
      - /examples/node-esm-top-level-await
      - /examples/node-esm-tsconfig-paths
    schedule:
      interval: daily
    reviewers:
      - igalklebanov

  - package-ecosystem: bun
    directory: /examples/bun
    schedule:
      interval: daily
    reviewers:
      - igalklebanov

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    reviewers:
      - igalklebanov
