packages:
- ./examples/node-*

allowBuilds:
  better-sqlite3@12.6.0: true
  esbuild@0.23.1 || 0.25.1: true # vitest@4.0.14

blockExoticSubdeps: true

catalog:
  '@types/better-sqlite3': 7.6.13
  better-sqlite3: 12.6.0
  kysely: 0.28.9
  typescript: 5.9.3

minimumReleaseAge: 1440 # install package versions that are at least 1 day old (in minutes).

trustPolicy: no-downgrade # fail if there's a regression in attestation of packages.

trustPolicyExclude:
  - undici-types@6.21.0 # @neondatabase/serverless@1.0.1 - https://socket.dev/npm/package/undici-types/overview/6.21.0
