# https://docs.npmjs.com/trusted-publishers#github-actions-configuration
name: publish

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: read
  id-token: write  # Required for OIDC

jobs:
  npm:
    environment: release
    runs-on: ubuntu-latest

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@fe104658747b27e96e4f7e80cd0a94068e53901d # v2.16.1
        with:
          egress-policy: audit

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Install pnpm
        uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v4.4.0

      - name: Use Node.js
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: lts/*
          cache: "pnpm"

      - name: Install dependencies
        run: npm i -g npm@latest && pnpm i

      - name: Publish
        run: pnpm publish --no-git-checks # the workflow runs in a detached head state, so git checks fail
